/* V2.9 Department Router */
export const DEPARTMENT_ROUTES = { PM:'SECTION_01_PM', UIUX:'SECTION_02_UIUX', FRONTEND:'SECTION_03_FRONTEND', BACKEND:'SECTION_04_BACKEND', QA:'SECTION_05_QA', SEO:'SECTION_06_SEO', MARKETING:'SECTION_07_MARKETING', CLIENT_MANAGEMENT:'SECTION_08_CLIENT_MANAGEMENT', CONTENT:'SECTION_09_CONTENT', ARCHIVE:'SECTION_10_ARCHIVE' };
export function routeTask(task){ return { ...task, section: DEPARTMENT_ROUTES[task.department] || 'SECTION_01_PM', routedAt: new Date().toISOString() }; }
